# Shell aliases
alias a='aria2c'
alias boincmgr='cd /home/lite/.boinc/ && boincmgr'
alias boincd='boinc_client --allow_remote_gui_rpc --dir /home/lite/.boinc --daemon'
alias clock='clockywock'
alias count='find . -type f | wc -l'
alias curlip='curl ifconfig.co'
alias dfa='df  --total -l -xtmpfs -x rootfs -x devtmpfs -h | grep --color=never -e t'
alias dockerkiller='docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)'
alias du='du -hs'
alias dir='ls --color=auto --format=vertical'
alias egrep='egrep --color=auto'
alias f='find / -iname 2>/dev/null'
alias fgrep='fgrep --color=auto'
alias joystick='sudo xboxdrv --detach-kernel-driver --led 2 --silent'
alias l='ls'
alias l.="ls -a | egrep '^\.'"
alias la='ls -a'
alias ll='ls -lah'
alias ls='ls --color=auto'
alias hubble='sshfs root@hubble:/ /home/lite/hubble/'
alias mirrors='sudo reflector --score 100 --fastest 25 --sort rate --save /etc/pacman.d/mirrorlist --verbose'
alias m='mplayer'
alias merge='xrdb -merge ~/.Xresources'
#alias painkiller='wine "c:\Program Files\Painkiller Lite\Bin\Painkiller.exe" -lscripts PKPlus.pak'
alias p='sudo pacman'
alias pps='pacman -Ss'
alias pu='sudo powerpill -Syu'
alias replaygain='metaflac --add-replay-gain'
alias scannetwork='sudo arp-scan --interface=enp1s0 --localnet'
alias search='grep -rnw . -e'
alias sshadd='eval "$(ssh-agent)" && ssh-add ~/.ssh/id_rsa'
alias t='timidity'
alias tetris='vitetris'
alias unbz='tar -jxvf'
alias unixtime='date +%s'
alias ungz='tar -xzvf'
alias untar='tar -xvf'
alias vdir='ls --color=auto --format=long'
alias vim='nvim'
alias y='yaourt'
alias ys='yaourt -Ss'
alias yu='yaourt -Syu --aur'
