# Shell aliases
alias a='aria2c'
alias ccat='pygmentize'
alias clock='clockywock'
alias corefreq-init='sudo modprobe corefreqk && sudo systemctl start corefreqd && corefreq-cli'
alias count='find . -type f | wc -l'
alias curlip='curl ifconfig.co'
alias dfa='df  --total -l -xtmpfs -x rootfs -x devtmpfs -h | grep --color=never -e t'
alias dockerkiller='docker stop $(docker ps -a -q) && docker rmi $(docker images -q) --force'
alias du='du -hs'
alias dir='ls --color=auto --format=vertical'
alias egrep='egrep --color=auto'
alias f='find / -iname 2>/dev/null'
alias fgrep='fgrep --color=auto'
alias greg="grep --color=auto"
alias joystick='sudo xboxdrv --detach-kernel-driver --led 2 --silent'
alias l='ls'
alias l.="ls -a | egrep '^\.'"
alias la='ls -a'
alias ll='ls -lah'
alias ls='ls --color=auto'
alias hubble='sshfs -p 122 root@x.gfax.ch:/ ~/hubble/'
alias mirrors='sudo reflector --score 100 --fastest 25 --sort rate --save /etc/pacman.d/mirrorlist --verbose'
alias m='mplayer'
alias merge='xrdb -merge ~/.Xresources'
#alias painkiller='wine "c:\Program Files\Painkiller Lite\Bin\Painkiller.exe" -lscripts PKPlus.pak'
alias p='sudo pacman'
alias pps='pacman -Ss'
alias pu='sudo powerpill -Syu'
alias replaygain='metaflac --add-replay-gain'
alias scannetwork='sudo arp-scan --interface=enp1s0 --localnet'
alias search='grep -rnw . -e'
alias sshadd='eval "$(ssh-agent)" && ssh-add ~/.ssh/id_rsa'
alias t='timidity'
alias tetris='vitetris'
alias unbz='tar -jxvf'
alias unixtime='date +%s'
alias ungz='tar -xzvf'
alias untar='tar -xvf'
alias vdir='ls --color=auto --format=long'
alias vim='nvim'
alias y='pikaur'
alias ys='pikaur -Ss'
alias yu='pikaur -Syu'
