# Shell aliases
alias a='aria2c'
alias boincd='boinc_client --allow_remote_gui_rpc --dir /home/lite/.boinc --daemon'
alias clock='clockywock'
alias cronroot='env VISUAL=vim crontab -e'
alias count='find . -type f | wc -l'
alias curlip='curl ifconfig.co'
alias dfa='df  --total -l -xtmpfs -x rootfs -x devtmpfs -h | grep --color=never -e t'
alias dockerkiller='docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)'
alias du='du -hs'
alias dir='ls --color=auto --format=vertical'
alias egrep='egrep --color=auto'
alias f='find / -iname 2>/dev/null'
alias fgrep='fgrep --color=auto'
alias l='ls'
alias l.="ls -a | egrep '^\.'"
alias la='ls -a'
alias ll='ls -lah'
alias ls='ls --color=auto'
alias m='mplayer'
alias merge='xrdb -merge ~/.Xresources'
alias p='pacman'
alias pps='p -Ss'
alias rtorrent='rtorrent -o http_capath=/etc/ssl/certs'
alias replaygain='metaflac --add-replay-gain'
alias s='screen -r'
alias search='grep -rnw . -e'
alias sshadd='eval "$(ssh-agent)" && ssh-add ~/.ssh/id_rsa'
alias svim='sudo vim'
alias t='tmux attach'
alias tetris='vitetris'
alias unbz='tar -jxvf'
alias unixtime='date +%s'
alias ungz='tar -xzvf'
alias unixtime='date +%s'
alias untar='tar -xvf'
alias vdir='ls --color=auto --format=long'
alias y='yaourt'
alias ys='yaourt -Ss'
alias yu='yaourt -Syu'
