theme = "base16_transparent"

[editor]
auto-pairs = false
line-number = "relative"
mouse = false
#rulers = [80, 120]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
#wrap-indicator = ""  # set wrap-indicator to "" to hide it

[keys.insert]
"C-c" = "normal_mode"

[keys.normal]
A-x = ["extend_to_line_bounds", "trim_selections"]
C-down = ["extend_to_line_bounds", "delete_selection", "paste_after"] # move line up
C-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"] # move line down
#C = "change_selection_noyank" # don't clobber register, todo: find an unused keybinding for this
D = "delete_selection_noyank" # don't clobber register
# Replace a character from normal mode? https://github.com/helix-editor/helix/pull/4709
#f = ["insert_mode", "@<ret>", "normal_mode"]
backspace = "insert_mode"

[keys.select]
D = "delete_selection_noyank"
