theme = "base16_transparent"

[editor]
auto-pairs = false
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.insert]
"C-c" = "normal_mode"

[keys.normal]
C = "change_selection_noyank"
D = "delete_selection_noyank"
# https://github.com/helix-editor/helix/pull/4709
#f = ["insert_mode", "@<ret>", "normal_mode"]
A-x = ["extend_to_line_bounds", "trim_selections"]
backspace = "insert_mode"
